server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            client-id: messaging-client
            client-secret: secret
            client-name: oidc-client-authentication
            provider: oidc-provider
            scope: openid,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/messaging-client
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
        provider:
          oidc-provider:
            issuer-uri: http://localhost:9000
#          spring:
#            authorization-uri: "http://localhost:9000/oauth2/authorize"
#            token-uri: "http://localhost:9000/oauth2/token"
#            user-info-uri: "http://localhost:9000/userinfo"
#            user-info-authentication-method: "header"
#            jwk-set-uri: "http://localhost:9000/oauth2/jwks"
#            user-name-attribute: "user"

