server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: oath2-server
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - client_credentials
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/messaging-client
                - http://localhost:8080/authorized
              post-logout-redirect-uris:
                - http://localhost:8080/logged-out
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true